swagger: '2.0'
info:
  title: HTTP API Console checkers.checkers
  name: ''
  description: ''
paths:
  /suhel-kap/checkers/checkers/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /suhel-kap/checkers/checkers/system_info:
    get:
      operationId: Query_SystemInfo
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              SystemInfo:
                type: object
                properties:
                  nextId:
                    type: string
                    format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  QueryGetSystemInfoResponse:
    type: object
    properties:
      SystemInfo:
        type: object
        properties:
          nextId:
            type: string
            format: uint64
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  checkers.Params:
    type: object
  checkers.SystemInfo:
    type: object
    properties:
      nextId:
        type: string
        format: uint64
  MsgCreatePostResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
  Params:
    type: object
